In [1]:
import numpy as np

arr = np.random.randint(0, 51, size=20)

print("Вихідний масив:")
print(arr)

threshold = int(input("Введіть порогове значення: "))

count = np.sum(arr > threshold)

print(f"Кількість елементів більших за {threshold}: {count}")

max_value = np.max(arr)
max_position = np.argmax(arr)

print(f"Максимальне значення: {max_value}")
print(f"Позиція першої появи: {max_position}")

sorted_arr = np.sort(arr)[::-1]

print("Масив за спаданням:")
print(sorted_arr)

Вихідний масив:
[ 1  8 48 12 43  0 17 40 31  9 39  7 40 46 46  3  2 15 29 29]


Введіть порогове значення:  1


Кількість елементів більших за 1: 18
Максимальне значення: 48
Позиція першої появи: 2
Масив за спаданням:
[48 46 46 43 40 40 39 31 29 29 17 15 12  9  8  7  3  2  1  0]


In [2]:
import numpy as np

lower = int(input("Введіть нижню межу: "))
upper = int(input("Введіть верхню межу: "))

matrix = np.random.randint(lower, upper + 1, size=(5, 5))

print("Вихідна матриця:")
print(matrix)

diagonal = np.diag(matrix)

print("Головна діагональ:")
print(diagonal)

diagonal_sum = np.sum(diagonal)

print("Сума головної діагоналі:")
print(diagonal_sum)

modified_matrix = matrix.copy()

modified_matrix[np.triu_indices(5, k=1)] = 0

print("Матриця після обнулення елементів вище головної діагоналі:")
print(modified_matrix)

Введіть нижню межу:  2
Введіть верхню межу:  2


Вихідна матриця:
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Головна діагональ:
[2 2 2 2 2]
Сума головної діагоналі:
10
Матриця після обнулення елементів вище головної діагоналі:
[[2 0 0 0 0]
 [2 2 0 0 0]
 [2 2 2 0 0]
 [2 2 2 2 0]
 [2 2 2 2 2]]


In [3]:
import numpy as np

start = int(input("Введіть початок діапазону: "))
end = int(input("Введіть кінець діапазону: "))

numbers = np.arange(start, end + 1)

matrix = numbers[:30].reshape(6, 5)

print("Матриця 6x5:")
print(matrix)

row_sums = np.sum(matrix, axis=1)

print("Суми елементів у кожному рядку:")
print(row_sums)

column_max = np.max(matrix, axis=0)

print("Максимальні значення за кожним стовпчиком:")
print(column_max)

start = int(input("Введіть початок діапазону: "))
end = int(input("Введіть кінець діапазону: "))

numbers = np.arange(start, end + 1)

matrix = numbers[:30].reshape(6, 5)

print("Матриця 6x5:")
print(matrix)

row_sums = np.sum(matrix, axis=1)

print("Суми елементів у кожному рядку:")
print(row_sums)

column_max = np.max(matrix, axis=0)

print("Максимальні значення за кожним стовпчиком:")
print(column_max)

Введіть початок діапазону:  1
Введіть кінець діапазону:  2


ValueError: cannot reshape array of size 2 into shape (6,5)

In [4]:
import numpy as np

lower = int(input("Введіть нижню межу: "))
upper = int(input("Введіть верхню межу: "))

arr = np.random.randint(lower, upper + 1, size=15)

print("Вихідний масив:")
print(arr)

negative_elements = arr[arr < 0]

print("Від'ємні елементи:")
print(negative_elements)

modified_arr = arr.copy()
modified_arr[modified_arr < 0] = 0

print("Масив після заміни від'ємних елементів на нулі:")
print(modified_arr)

zero_count = np.sum(modified_arr == 0)

print("Кількість нульових елементів:")
print(zero_count)

Введіть нижню межу:  1
Введіть верхню межу:  30


Вихідний масив:
[15 16  2 14  2 24 30 18 21  7 10 21 18 13 21]
Від'ємні елементи:
[]
Масив після заміни від'ємних елементів на нулі:
[15 16  2 14  2 24 30 18 21  7 10 21 18 13 21]
Кількість нульових елементів:
0


In [5]:
import numpy as np

length = int(input("Введіть довжину масивів: "))

arr1 = np.random.randint(0, 11, size=length)
arr2 = np.random.randint(10, 21, size=length)

print("Перший масив:")
print(arr1)

print("Другий масив:")
print(arr2)

combined = np.concatenate((arr1, arr2))

print("Об'єднаний масив:")
print(combined)

addition = arr1 + arr2
difference = arr1 - arr2

print("Поелементне додавання:")
print(addition)

print("Поелементна різниця:")
print(difference)

Введіть довжину масивів:  2


Перший масив:
[5 1]
Другий масив:
[10 20]
Об'єднаний масив:
[ 5  1 10 20]
Поелементне додавання:
[15 21]
Поелементна різниця:
[ -5 -19]


In [ ]:
import numpy as np

rows = int(input("Введіть кількість рядків вихідної матриці: "))
cols = int(input("Введіть кількість стовпчиків вихідної матриці: "))

matrix = np.arange(1, rows * cols + 1).reshape(rows, cols)

print("Вихідна матриця:")
print(matrix)

new_rows = int(input("Введіть нову кількість рядків: "))
new_cols = int(input("Введіть нову кількість стовпчиків: "))

new_matrix = matrix.reshape(new_rows, new_cols)

print("Нова матриця:")
print(new_matrix)

row_min = np.min(new_matrix, axis=1)
row_max = np.max(new_matrix, axis=1)

print("Мінімальні значення в кожному рядку:")
print(row_min)

print("Максимальні значення в кожному рядку:")
print(row_max)

total_sum = np.sum(new_matrix)

print("Загальна сума всіх елементів:")
print(total_sum)

Введіть кількість рядків вихідної матриці:  4
Введіть кількість стовпчиків вихідної матриці:  5


Вихідна матриця:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
